stages:
  - install
  - gotest
  - build

before_install:
  stage: install
  script:
    - GOPROXY=https://goproxy.cn go mod tidy
  tags:
    - go

go_test_other:
  stage: gotest
  script:
    - go test --race -cpu=1,2,4 -covermode=atomic -v ./test/...
  tags:
    - go

build-test:
  stage: build
  script:
    - make && make clean
  tags:
    - go
